# Generated by Django 5.2.7 on 2025-12-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='open_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='working_hours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
