# Generated by Django 5.2.7 on 2025-12-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_place_open_state_place_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(db_index=True, default='sights', max_length=50),
        ),
    ]
