# Generated by Django 5.2.7 on 2025-12-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.IntegerField(db_index=True)),
                ('street_name', models.CharField(max_length=255)),
                ('lat_snode', models.FloatField()),
                ('long_snode', models.FloatField()),
                ('lat_enode', models.FloatField()),
                ('long_enode', models.FloatField()),
            ],
        ),
    ]
