# Generated by Django 5.2.7 on 2025-12-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trafficsegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsegment',
            name='lat_snode',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trafficsegment',
            name='long_snode',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trafficsegment',
            name='street_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
