# Generated by Django 5.2.7 on 2025-12-11 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destinations',
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('arrival_time', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('highlight', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('travel_info', models.JSONField(blank=True, default=dict, null=True)),
                ('order', models.IntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='trips.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
